In [20]:
#144335611 332851271 99998593 925686214

import numpy as np
import matplotlib.pyplot as plt


In [21]:
mat = np.array([[6,5,1,5],[1,1,0,7],[1,0,1,1],[0,0,0,1]], dtype=)
print(mat)


[[6. 5. 1. 5.]
 [1. 1. 0. 7.]
 [1. 0. 1. 1.]
 [0. 0. 0. 1.]]


In [22]:
pow=np.linalg.matrix_power(mat,925686214 )

c:\Users\Dell Latitude 5420\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\linalg\linalg.py:657: RuntimeWarning: overflow encountered in matmul
  result = z if result is None else fmatmul(result, z)
c:\Users\Dell Latitude 5420\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\linalg\linalg.py:654: RuntimeWarning: overflow encountered in matmul
  z = a if z is None else fmatmul(z, z)
c:\Users\Dell Latitude 5420\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\linalg\linalg.py:654: RuntimeWarning: invalid value encountered in matmul
  z = a if z is None else fmatmul(z, z)
c:\Users\Dell Latitude 5420\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\linalg\linalg.py:657: RuntimeWarning: invalid value encountered in matmul
  result = z if result is None else fmatmul(result, z)


In [23]:
pow

array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

In [24]:
ini=np.array([144335611,332851271,99998593,1])
res=np.dot(pow,ini)
res

array([nan, nan, nan, nan])

In [25]:
-5%2

1